# Generated by Django 3.0.8 on 2020-08-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(db_column='Photo', default='default.jpg', upload_to='profile_pics'),
        ),
    ]
